apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: myapp-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/myapp/env/prod
    repoURL: https://github.com/paichayon321/tekton-pipeline.git
    targetRevision: main
  syncPolicy:
    automated: {}
