apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: custom-approval
spec:
  results:
  - name: approve_result
  params:

  - name: recipients
    type: string
    description: recipient email addresses
  - name: pipeline_name
    type: string
  - name: pipelinerun_name
    type: string  
  - name: image_tag
    type: string 
  - name: environment
    type: string 
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - image: docker.io/paichayon1/tekton-approve:0.7
    name: wait-approve
    script: |
      echo $(params.recipients)
      echo $(params.pipeline_name)
      echo $(params.pipelinerun_name)
      echo $(params.image_tag)
      echo $(params.environment)

      code=$(shuf -i 1000000000000000-9999999999999999 -n 1)
      cicd_ns="cicd"
      basedomain="$cicd_ns.apps.cluster-h942w.h942w.sandbox2265.opentlc.com"
      echo "code number: $code" 
      approve_link="<b>Pipeline name:</b> $(params.pipeline_name) <br><b>Image tag:</b> $(params.image_tag) <br><b>Environment:</b> $(params.environment) <br><b>Pipeline Approve Code:</b> $code<p>Click link below to Approve:<br>http://$(params.pipelinerun_name)-wait-for-approve-pod-$basedomain"
      python sendgmail.py "$user" "$password" "$(params.recipients)" "PipelineSystem - Approve Code for $(params.pipeline_name)" "$approve_link" 
      python approval.py "$code" "$(params.image_tag)" "$(params.environment)"
      
      approve_result=$(cat result.txt)
      echo $approve_result
      printf "%s" "${approve_result}" > "$(results.approve_result.path)"


