apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-pat-secret
  namespace: cicd
spec:
  encryptedData:
    GIT_CREDS_PSW: AgCojfIDl1K18Jb3AncevrJ0YZQKoC/OlCPtw4jv19SSENalpljVVCqCo11sKkSwnT64Vd5xnWDjoqm66mK7a3EPMzooEZDnJNzrwKZ2qmSToU41w5oMkvHzpW5ozswzw/u/jlg81MtclcLaAw/oBkAXqWgSJ5/OAYDV59PJ4t1bFSSIDPlro5Oa4AtbQwfh+RYoCHmKXd5mqAiPHrhoU2hahd2nQXlC1le8QDfNxTZP3XpwsYgvPPz4hN4M7uoUvYrSVuW/qSQqMx3OVsaCvir20H60OZnvSsZi/DPNbdiL1E7VWFkAM9dPlQOtSvW90gr3ze5SmTC1b31QYOSDHcVeh1WW2Dd/JJPq92VTh/peOQzTEG0mstyuo6INCOHNdHTleOVDmuu/+wO6dX7TXAQud1O+BqxkDGC6W4zBoP4wTGfvec46KmXAaNfYsSo6eWgkyXAPe6roQ+6yg0pxqXRnPrwOvlCeycsbICOcNfl2TAFtMBrFjEn1uAbtDEMvAjpYzcKnw6zW/rImDOKQ+Gx8DFEDhnpq5WwNHxKLTaFRMz3mt+hXubTGeDqm+9N5vO4rnGm6XSsEer0JhaPY7WumMj8/YZadWV1GPfXGWHF3Hby1kwQRKbKivL1DzpwrHO0W7/+GbCDHXX9O94IDfRlJPR3cSkqiw9MmOr+Gqikea/3T3AX/TfBs5hfcBz9AvqAes8BayVTneQgYYdOD0ySmmY4TmlAT3H6eRfvkKDecXWK6bkexJDXQ
    GIT_CREDS_USR: AgCAj2L//NtQQBFBSrd1T6sdNbnjlRXG5bpD9YRYqDGjkY5qqzs0oMffumH0EZcd2qyLu1OIzlfMcDZ9DQZ1kiAJ01aztNp2+2JTISAAYc4C5blTZTpw/tcOV3KFspJPd1anpErRbO02XjtuSqin13A48ADCzZ5uWLrLRcz2/GWsvf61YCwEQULOCwq2gKNICJboxpbLGKQ3Gf+6GKxA4e31mM+drrAcDS+1Qc68bI0Tr50ME8j4/r5DXPNg1cLaGwaa5aR6pzXlXL+vlssY/dRbAvDaLqC8M+tO25GPbu+Y3GBJy9LxQprEsHUlQyaq5AgHogLc7w5Kz9JyOQz32rtOqZq5pSw7fpsaHU7pv+GjPzWWLp3MH902SyZhTOi96ys0hih4Z9BSmgk4Vo8wI8LE80x+KjhEBNICFZbgXsAVNI+D04mPSHCRJXrPTeiaF2kdEv39A6fFpPCT1WYyz1ZUEkJ4h8pg5gdJLpwpyBh8tnfzgZusen+b5epehD80p7hvwvoxhr1lzBEHCR/zDCaALZREb62aNY/latlutBs8LM7cXRr5eq28ino5Yqaj6A/FSGrhzh5ewAlOvSB49XpqWBz11wRc8Ayxh6wH2UefVjbGRx5vjVFY8TYaKMblD+YSS7JxGxjkKTS+/DF3vDiQfAQbdLyT8arYQIEPl6iBtGIFh6EAVBCtNkrCUOO6N4paWhyzW5zzOlE0VwQ=
  template:
    metadata:
      creationTimestamp: null
      name: github-pat-secret
      namespace: cicd
    type: Opaque

