kind: Secret
apiVersion: v1
metadata:
  name: sonarqube-secret
  namespace: cicd
data:
  SONAR_HOST_URL: >-
    aHR0cDovL2h0dHA6Ly9zb25hcnF1YmUtcm91dGUtY2ljZC10b29scy5hcHBzLmNsdXN0ZXItaDk0MncuaDk0Mncuc2FuZGJveDIyNjUub3BlbnRsYy5jb20v
  SONAR_LOGIN_TOKEN: c3F1XzJjYjg4MWY0YjE1M2Y0OWFjYTA2ZDMxYTc2YTI4YjRhMGM1ZmNjMWQ=
type: Opaque
