apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "update-manifest-task"
spec:
  results:
  - name: environment
  - name: image_tag
  params:
  - name: git_repo_name
  - name: environment
  - name: image_tag
  - name: image_repo_url
  description: >-
    update-manifest-task
  stepTemplate:
    envFrom:
      - secretRef:
          name: github-pat-secret  # github-pat
  steps:
    - name: clone-platform-repo
      env:
        - name: git_repo_name
          value: $(params.git_repo_name) 
        - name: environment
          value: $(params.environment) 
        - name: image_tag
          value: $(params.image_tag)               
        - name: deploy_env
      image: docker.io/paichayon1/multitools:ubi7
      script: |
        #!/usr/bin/env bash
        echo "####################"
        echo $(params.environment)
        echo "####################"

        if [[ $(params.environment) == dev ]]; then
            deploy_env=dev
        elif [[ $(params.environment) == tags ]]; then
            deploy_env=sit
        elif [[ $(params.environment) == uat ]]; then
            deploy_env=uat
        elif [[ $(params.environment) == prod ]]; then
            deploy_env=prod
        elif [[ $(params.environment) == dr ]]; then
            deploy_env=dr
        else
            exit 1
        fi  

        git clone https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/paichayon321/tektondeom-temp.git
        cd tektondeom-temp
        git checkout origin/main
        git config --global user.name "tekton_pipeline"
        git config --global user.email "tektonPipeline@domain.local"
        echo "###########################"
        echo "will update $(params.image_repo_url)/$(params.git_repo_name):$(params.image_tag) on $deploy_env"
        echo "###########################"
        yq -i '.spec.template.spec.containers[0].image = "$(params.image_repo_url)/$(params.git_repo_name):$(params.image_tag)"' ./app/myapp/env/$deploy_env/deployment.yaml
        git add --ignore-errors ./app/myapp/env/$deploy_env/deployment.yaml
        git commit -m "update image $(params.image_repo_url)/$(params.git_repo_name):$(params.image_tag) on $deploy_env"
        git push https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/paichayon321/tektondeom-temp.git HEAD:main

        printf "%s" "$deploy_env" > "$(results.environment.path)"
        printf "%s" "$(params.image_repo_url)/$(params.git_repo_name):$(params.image_tag)" > "$(results.image_tag.path)"



        

