apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-sit
  namespace: openshift-gitops
spec:
  destination:
    namespace: myapp-sit
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/myapp/env/sit
    repoURL: https://github.com/paichayon321/tektondeom-temp.git
    targetRevision: main
  syncPolicy:
    automated: {}
