apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: myapp-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/myapp/env/dev
    repoURL: https://github.com/paichayon321/tektondeom-temp.git
    targetRevision: main
  syncPolicy:
    automated: {}
